### ISSUE TITLE
게시글 삭제메서드 작성 관련으로 질문이 있습니다.

### ISSUE THREAD

**Issue by jihyeon4956** [jihyeon4956/Spring-Lv1_Board#1]
```
public class BoardController { 
   // 메모 삭제하기
    @DeleteMapping("/boards/{id}")
    public String deleteMemo(@PathVariable Long id, @RequestBody BoardRequestDto requestDto) { // 여기에 String password 하고싶었음
        return boardService.deleteMemo(id, requestDto);  //
    }
}

```

```
public class BoardService {
    // 삭제
    public String deleteMemo(Long id, BoardRequestDto requestDto) {
        // 해당 메모가 DB에 존재하는지 확인
        String password = requestDto.getPassword();
        Board board = findBoard(id);

        if(!passwordEncoder.matches(password, board.getPassword())) { // (평문, 암호문)
            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다");
        }

        boardRepository.delete(board);
        return "게시글 삭제 완료";
    }
}
```

위의 코드에서 단순 삭제만 진행하려고 했는데 삭제시에도 게시글을 작성할 때 생성했던 비밀번호의 검증이 필요합니다.
저는 게시글id와 password 두가지만 가져오고 싶었으나 password만 단독으로 받아오기 어려워서 "BoardRequestDto"를 가져온 후 거기서 password를 꺼내왔습니다.
지금은 저장된 내용이 별로없지만 하나의 게시글에 여러 요소(ex. 작성자, 생년월일, 닉네임, 제목, 내용, ... , )등이 들어가서 메모리 할당이 커진다면 이 모든 내용을 가져온 후에 password만 뽑아내는건 비효율적이지 않나 싶습니다.

<질문>
1. 삭제처리에 사용되는 id, password 딱 두가지만 가져올 수 있는 방법이 존재하는지
2. 현업에서는 어떤식으로 파라미터를 받아오는게 보편적인지

이 두가지를 알고 싶습니다.
감사합니다.

**Comment by Nhahan** [comment]
1. 존재하지만, 보통 아이디는 path variable로 받고, password는 바디로 받게 됩니다.
2. dto를 password만 있는 것으로 따로 만들어도 되고, 안만들어도 됩니다. 장단점이 있습니다. 따로 만들면 깔끔해지겠지만 파일이 너무 많아지는 단점이 있고, 따로 안만들면 파일이 적어지는 장점이 있어요. 취향인 것 같습니다. 하지만 따로 만드는게 면접관 입장에서는 가장 좋아할거에요.
