### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by Jang-JIye** [jihyeon4956/Spring-Lv1_Board#2]
Restful한 설계를 잘 했나요?
- URI를 통한 자원 식별과 HTTP 메서드 사용에 대한 측면에서 대부분의 RESTful 원칙을 준수하고 있습니다.
- "boards"로 시작하는 URI
- GET, POST, PUT, DELETE 메서드를 사용합니다.
- password를 보안처리하기 위해 config에서 passwordEncoder()를 사용하여 암호화하고 있습니다.
- Responsebody를 사용해서 Http요청의 지정된 바디로 본문을 클라이언트에 전달하고 있습니다.

API 명세서에 따른 설계가 잘 되어있나요?
 - 네. 명세서에 작성된 response, request 를 요청하고 값을 받아오고 있고, Http매서드도 알맞게 사용하고 있습니다.
 - usecase 다이어그램이 한눈에 사용자와 시스템 간의 상호작용을 볼 수 있어서 좋았습니다.

예외처리가 미흡한 부분은 없나요?
- Else throw new IllegalArgumentException으로 조건에 맞지 않는 케이스를 예외처리를 하고 있습니다. throw 된 예외처리 메시지를 통해 무엇이 잘 못 되었는지 확인할 수 있었습니다.

**Comment by Nhahan** [comment]
전체적으로 너무 잘하셨네요.
1주차에 이 정도면 너무 훌륭하다고 생각합니다! 😆
